// Generated by scripts/bump-version-pre-commit.js.
// Do not edit manually.

export default function getVersion(): string {
    return '2.50.89-feature_elevation_store_gate2_5_6_sol_failure2.b1a52af1';
}
